### PR TITLE
replaced /" with '

### PR DESCRIPTION
**Pull request by daviddicken**
Made code easier to read

### CODE REVIEW

**Comment by someuser3** [comment]
Cannot figure out how to merge my five versions with your change. Added your change to mine manually... :(

**Comment by someuser3** [comment]
Or did I just fixed it? :)

**Comment by someuser3** [comment]
That was hard because I've pushed eight commits since I merged your first pull request while you still worked on the eight-versions-old file:
image

To avoid this in the future we should pull latest changes from github right before making ours and to not wait to push the changes upstream. Lesson here - working alone is easy, working with others requires more work. :)

**Comment by someuser3** [comment]
This is how it looks now:
image
You can see your two merges and eleven of my commits in between. :)

**Comment by daviddicken** [comment]
Sounds like it wouldn't be a bad idea for me to practice merging files on my repo.

**Comment by someuser3** [comment]
Definitely! I'll pull your lab9 later this weekend.

**Pull request merged**
